[workspace]
members = [ "contracts/*" ]

[workspace.package]
authors = ["Murad Karammaev <muradkarammaev@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
version = "0.1.0"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
