on:
  push:
    branches:
      - '**'

name: tests

jobs:
  clippy:
    name: Actions - clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.73.0
          components: clippy
          profile: minimal
          override: true
      - run: make clippy

  rustfmt:
    name: Actions - rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.73.0
          components: rustfmt
          profile: minimal
          override: true
      - run: make fmt

  unit-test:
    name: Actions - unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.73.0
          profile: minimal
      - run: make test
        env:
          RUST_BACKTRACE: 1
